%%LOGISTIC REGRESSION FOR THE HANDWRITTEN DATA 
%%EXTRACT THE DATA THAT CAN BE USED FOR THE CLASSIFICATION
%%MCONFUSION FEATURES FROM THE EXTRACTED FEATURES FOR THE USE
%%MAKE THE CONFUSION MATRIX
